SUCCESS = False
ERROR = True

DELETE_AFTER_MINUTES = 15
TIME_LOCK_MINUTES = 2
ATTEMPTS_INTERVAL = 3
NUM_OF_ATTEMPTS = 3

MINIMUM_CONFIRMATIONS = 1
MAX_AMOUNT = 0.1

API_KEY_HEADER = "X-API-Key"

EPICBOX_DOMAIN = 'epicpost.stackwallet.com'
EPICBOX_PORT = 0

SECRETS_PATH_PREFIX = 'Wallets/'
WALLETS = ['faucet_1', 'faucet_2']
