# Generated by Django 4.1.3 on 2023-02-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_api_key', models.CharField(max_length=128)),
                ('link_domain', models.CharField(default='giverofepic.give', max_length=64)),
                ('link_prefix', models.CharField(default='giverofepic.com/giveaway', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(default='EPIC', max_length=10)),
                ('address', models.CharField(help_text='receiver wallet address', max_length=128)),
                ('value', models.DecimalField(decimal_places=3, help_text='amount of currency to send', max_digits=16)),
                ('event', models.CharField(default='Giveaway', max_length=64)),
            ],
        ),
    ]
