# Generated by Django 4.1.3 on 2023-02-08 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_api_key', models.CharField(max_length=128)),
                ('short_link', models.CharField(default='', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reusable', models.IntegerField(default=0, null=True)),
                ('personal', models.BooleanField(default=True)),
                ('currency', models.CharField(default='EPIC', max_length=10)),
                ('claimed', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(default=datetime.datetime(2023, 2, 8, 21, 52, 14, 775425, tzinfo=datetime.timezone.utc))),
                ('address', models.CharField(help_text='receiver wallet address', max_length=128)),
                ('amount', models.DecimalField(decimal_places=3, help_text='amount of currency to send', max_digits=16)),
                ('event', models.CharField(default='Giveaway', max_length=64)),
            ],
        ),
    ]
