# Generated by Django 4.1.3 on 2023-02-07 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='link_lifetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 21, 47, 37, 531568, tzinfo=datetime.timezone.utc)),
        ),
    ]
