# Generated by Django 4.1.3 on 2023-02-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_code_link_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='already_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='code',
            name='link_lifetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 21, 51, 6, 438854, tzinfo=datetime.timezone.utc)),
        ),
    ]
