# Generated by Django 4.1.3 on 2023-02-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_code_already_claimed_alter_code_link_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='link_lifetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 21, 51, 13, 115279, tzinfo=datetime.timezone.utc)),
        ),
    ]
