# Generated by Django 4.1.3 on 2023-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_rename_short_link_link_ready_link_link_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='event',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
