# Generated by Django 4.1.3 on 2023-02-16 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_alter_link_currency_alter_link_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='currency',
            field=models.CharField(default='EPIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='event',
            field=models.CharField(default='giveaway', max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 22, 13, 13, 919635, tzinfo=datetime.timezone.utc)),
        ),
    ]
