# Generated by Django 4.1.3 on 2023-02-07 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_alter_code_link_lifetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='value',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='code',
            name='link_lifetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 21, 55, 26, 145963, tzinfo=datetime.timezone.utc)),
        ),
    ]
