# Generated by Django 4.1.3 on 2023-02-17 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_alter_link_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 12, 50, 26, 219916, tzinfo=datetime.timezone.utc)),
        ),
    ]
