# Generated by Django 4.1.3 on 2023-02-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0009_alter_link_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 5, 10, 234752, tzinfo=datetime.timezone.utc)),
        ),
    ]
