# Generated by Django 4.1.3 on 2023-02-20 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0010_alter_link_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 16, 55, 51, 439620, tzinfo=datetime.timezone.utc)),
        ),
    ]
