# Generated by Django 4.1.3 on 2023-02-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('last_success_tx', models.DateTimeField(blank=True, null=True)),
                ('TIME_LOCK_SECONDS', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='faucet.address')),
            ],
            bases=('faucet.address',),
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='faucet.address')),
            ],
            bases=('faucet.address',),
        ),
    ]
