# Generated by Django 4.1.3 on 2022-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpicBoxAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.CharField(max_length=256)),
                ('sender_address', models.CharField(max_length=256)),
                ('wallet_db_id', models.IntegerField()),
                ('tx_slate_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('tx_type', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('status', models.CharField(max_length=256)),
                ('slates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='default', max_length=128)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
