# Generated by Django 4.1.3 on 2022-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=24)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('last_success_tx', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('last_success_tx', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EpicBoxAddress',
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
    ]
