# Generated by Django 4.1.3 on 2022-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_connectionip_receiveraddress_delete_epicboxaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionip',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectionip',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiveraddress',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiveraddress',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
