# Generated by Django 4.1.3 on 2022-11-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_connectionip_is_banned_connectionip_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('last_success_tx', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectionIP',
        ),
        migrations.DeleteModel(
            name='ReceiverAddress',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='locked',
            new_name='is_locked',
        ),
        migrations.CreateModel(
            name='IPAddr',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.address')),
            ],
            bases=('wallet.address',),
        ),
        migrations.CreateModel(
            name='ReceiverAddr',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.address')),
            ],
            bases=('wallet.address',),
        ),
    ]
