# Generated by Django 4.1.3 on 2022-11-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallet_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletState',
        ),
    ]
