# Generated by Django 4.1.3 on 2022-11-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_walletstate_directory_alter_walletstate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
