# Generated by Django 4.1.3 on 2022-11-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transaction_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='slates',
            new_name='encrypted_slate',
        ),
    ]
