# Generated by Django 4.1.3 on 2022-11-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_slates_transaction_encrypted_slate'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletstate',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
