# Generated by Django 4.1.3 on 2022-11-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_walletstate_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletstate',
            old_name='directory',
            new_name='wallet_dir',
        ),
    ]
